name: Build & Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build app
        run: python build.py --platform windows

      - name: Install Inno Setup
        run: choco install innosetup -y

      - name: Build installer
        run: iscc installer.iss

      - name: Upload Windows installer
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: installer/ContiniumSetup.exe


  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y libegl1 libxkbcommon-x11-0
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build app
        run: python build.py --platform linux

      - name: Upload Linux build
        uses: actions/upload-artifact@v4
        with:
          name: linux-app
          path: dist/


  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          pip install -r requirements.txt
          pip install pyinstaller pillow

      - name: Build app
        run: python build.py --platform macos

      - name: Create DMG
        run: |
          hdiutil create \
            -volname Continium \
            -srcfolder dist/Continium.app \
            -ov -format UDZO \
            Continium.dmg

      - name: Upload macOS dmg
        uses: actions/upload-artifact@v4
        with:
          name: mac-installer
          path: Continium.dmg


  release:
    needs: [build-windows, build-linux, build-macos]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/windows-installer/ContiniumSetup.exe
            release/linux-app/**
            release/mac-installer/Continium.dmg